[package]
org = "ballerina"
name = "ldap"
version = "1.0.1"
authors = ["Ballerina"]
export=["ldap"]
keywords = ["ldap"]
repository = "https://github.com/ballerina-platform/module-ballerina-ldap"
license = ["Apache-2.0"]
distribution = "2201.8.0"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.lib"
artifactId = "ldap-native"
version = "1.0.1"
path = "../native/build/libs/ldap-native-1.0.1.jar"

[[platform.java21.dependency]]
groupId = "com.unboundid"
artifactId = "unboundid-ldapsdk"
version = "7.0.0"
path = "./lib/unboundid-ldapsdk-7.0.0.jar"
