[package]
org = "ballerina"
name = "ldap"
version = "0.8.0"
authors = ["Ballerina"]
export=["ldap"]
keywords = ["ldap"]
repository = "https://github.com/ballerina-platform/module-ballerina-ldap"
license = ["Apache-2.0"]
distribution = "2201.8.5"

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
groupId = "io.ballerina.lib"
artifactId = "ldap-native"
version = "0.8.0-SNAPSHOT"
path = "../native/build/libs/ldap-native-0.8.0-SNAPSHOT.jar"

[[platform.java17.dependency]]
groupId = "com.unboundid"
artifactId = "unboundid-ldapsdk"
version = "7.0.0"
path = "./lib/unboundid-ldapsdk-7.0.0.jar"
